server:
  port: 5000

db:
  uri: 'mongodb://localhost/timeTravel'

gClient:
  key: 'AIzaSyASjOrAMMu2RYKQBldqY1-ZTM3w0xv_YXk'
  id: '276997654254-mbmq2tgrj3dhkh48rs1dshtf2jfcfl48.apps.googleusercontent.com'
  secret: '5lITiLdw-GaTdfRWLqwg_X0T'
  url: 'https://localhost:5000'