server:
  port: 5000

db:
  uri: 'mongodb://localhost/timeTravel'

googleConfig:
  login_dialog_uri: 'https://accounts.google.com/o/oauth2/auth'
  client_key: 'AIzaSyASjOrAMMu2RYKQBldqY1-ZTM3w0xv_YXk'
  client_id: '276997654254-mbmq2tgrj3dhkh48rs1dshtf2jfcfl48.apps.googleusercontent.com'
  client_secret: '5lITiLdw-GaTdfRWLqwg_X0T'
  oauth_redirect_uri: 'http://localhost:4200/recipes'
  access_token_uri: 'https://accounts.google.com/o/oauth2/token'
  response_type: 'code'
  scopes: [
    'https://www.googleapis.com/auth/plus.login',
    'https://www.googleapis.com/auth/plus.profile.emails.read'
  ]
  grant_type: 'authorization_code'